title: Net Zero Toolkit - Card Game
description: The website for the card game supplied as part of the Scottish Episcopal Church's Net Zero Toolkit
baseurl: ""
url: "https://jeancarletta.github.io/SEC-Card-Game"
repository: JeanCarletta/SEC-Card-Game # for github-metadata
theme: just-the-docs
logo: ./graphics/PEG_logo.png


#footer_content: "Created 2023 by HeatHack in collaboration with the Provincial Environment Group.  :TODO: insert license with link, try to get logo in" 
# url: https://just-the-docs.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs
  


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red